name: nextjs/movies-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la
          docker build -t hugo2908/movies-app .
      - name: push the docker image
        id: push-docker-image
        run: docker push hugo2908/movies-app